---
version: "2.1"
services:
  installer:
    image: nicholaswilde/cryptpad
    container_name: cryptpad
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles  # optional
      - PUID=1000               # optional
      - PGID=1000               # optional
    volumes:
      - blob:/blob
      - block:/block
      - customize:/customize
      - config:/config
      - data:/data
      - datastore:/datastore
volumes:
  blob:
  block:
  customize:
  config:
  data:
  datastore:
