---
version: "2.1"
services:
  installer:
    image: nicholaswilde/cryptpad:latest
    container_name: cryptpad
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - blob:/blob
      - block:/block
      - customize:/customize
      - config:/config
      - data:/data
      - datastore:/datastore
volumes:
  blob:
  block:
  customize:
  config:
  data:
  datastore:
